# Generated by Django 3.2.25 on 2024-08-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='current_period_start',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='original_period_start',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_id',
        ),
    ]
